# Generated by Django 4.1.1 on 2022-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Adhar_id', models.CharField(max_length=50)),
                ('Room_no', models.CharField(max_length=50)),
                ('Time_in', models.DateTimeField(auto_now=True)),
                ('Contact', models.CharField(max_length=20)),
            ],
        ),
    ]
